Repository teamleadercrm/sdk-js, pull requests merged in 2019-02, with the labels that each got.

#43 [Feature] Make accessToken optional
  README.md
  package.json
  src/main.js
  src/utils/createRequestHeaders.js
  src/utils/mergeConfigurations.js
  test/utils/createRequestHeaders.test.js
  test/utils/mergeConfigurations.test.js
Labels: enhancement, frontend, ready

#44 [FIX] Pass down full configuration
  CHANGELOG.md
  package.json
  src/main.js
Labels: bug, frontend, ready

#45 Fix/normalize plugin default byId
  src/plugins/normalize.js
  test/plugins/normalize.test.js
Labels: bug, ready

#46 Update changelog for normalize byId fix
  CHANGELOG.md
  package.json
Labels: ready

#47 [FEATURE] Add additionalActions configuration
  CHANGELOG.md
  README.md
  package.json
  src/main.js
  test/main.test.js
Labels: enhancement, frontend, ready
